### ISSUE TITLE
Cusom Authetication Model

### ISSUE THREAD

**Issue by osinakayah** [zgabievi/laravel-promocodes#14]
I am using a different authentication model, it throws an exception saying the App\User cant be found.

[2017-10-02 02:15:10] local.ERROR: Class 'App\User' not found {"userId":1,"email":"osi@osi.com","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class 'App\\User' not found at /opt/lampp/htdocs/sendchow/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasRelationships.php:506)
[stacktrace]
#0 /opt/lampp/htdocs/sendchow/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasRelationships.php(310): Illuminate\\Database\\Eloquent\\Model->newRelatedInstance('App\\\\User')
#1 /opt/lampp/htdocs/sendchow/vendor/zgabievi/promocodes/src/Models/Promocode.php(60): Illuminate\\Database\\Eloquent\\Model->belongsToMany('App\\\\User', 'promocode_user')
#2 /opt/lampp/htdocs/sendchow/vendor/zgabievi/promocodes/src/Promocodes.php(133): Gabievi\\Promocodes\\Models\\Promocode->users()
#3 /opt/lampp/htdocs/sendchow/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Gabievi\\Promocodes\\Promocodes->check('9BNY-K3SW')
#4 /opt/lampp/htdocs/sendchow/vendor/zgabievi/promocodes/src/Traits/Rewardable.php(36): Illuminate\\Support\\Facades\\Facade::__callStatic('check', Array)
#5 /opt/lampp/htdocs/sendchow/vendor/zgabievi/promocodes/src/Traits/Rewardable.php(75): SendChow\\Modules\\Authentication\\Model\\UserMock->applyCode('9BNY-K3SW', NULL)
#6 /opt/lampp/htdocs/sendchow/SendChow/Modules/Authentication/Web/Controller/AuthenticationController.php(27): SendChow\\Modules\\Authentication\\Model\\UserMock->redeemCode('9BNY-K3SW')
#7 [internal function]: SendChow\\Modules\\Authentication\\Web\\Controller\\AuthenticationController->login(Object(SendChow\\Modules\\Authentication\\Request\\LoginRequest))
#8 /opt/lampp/htdocs/sendchow/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#9 /opt/lampp/htdocs/sendchow/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('login', Array)

**Comment by jsdecena** [comment]
@zgabievi You can set your user in https://github.com/zgabievi/laravel-promocodes/blob/master/config/promocodes.php#L63
